name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        run: equivs-build no-ubuntu-firefox.equivs
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            LICENSE
            no-ubuntu-firefox_*_all.deb
            no-ubuntu-firefox_*_amd64.buildinfo
            no-ubuntu-firefox_*_amd64.changes
